apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::211125613373:role/eks-admin-role
      username: eks-admin-role
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::211125613373:user/admin-user
      username: admin-user
      groups:
        - system:masters
