name: Trigger Jenkins Build

on:
  push:
    branches: ["main"]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve CSRF Crumb
        id: crumb
        run: |
          JENKINS_URL="http://ec2-52-201-101-219.compute-1.amazonaws.com:8080"
          CRUMB=$(curl -s --fail \
            -u "jenkins_project:${{ secrets.JENKINS_API_TOKEN }}" \
            "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,':',//crumb)")
          if [ $? -eq 0 ]; then
            echo "crumb=$CRUMB" >> $GITHUB_OUTPUT
          else
            echo "Failed to retrieve CSRF crumb"
            exit 1
          fi
      - name: Trigger Jenkins Job
        run: |
          echo "Triggering Jenkins build..."
          curl -X POST \
            -u "jenkins_project:${{ secrets.JENKINS_API_TOKEN }}" \
            -H "${{ steps.crumb.outputs.crumb }}" \
            "http://ec2-52-201-101-219.compute-1.amazonaws.com:8080/job/autodeploy1/buildWithParameters?token=devsecops_build"
