name: Trigger Jenkins Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://ec2-52-201-101-219.compute-1.amazonaws.com:8080/job/autodeploy1/buildWithParameters?token=devsecops_build" \
          --user "my-jenkins-user:${{ secrets.JENKINS_API_TOKEN }}"
